### ISSUE TITLE
New nvim disable/enable approach

### ISSUE THREAD

**Issue by mario-amazing** [WhoIsSethDaniel/toggle-lsp-diagnostics.nvim#5]
Maybe you can think about this realization?

https://github.com/neovim/neovim/issues/14825#issuecomment-1196644699

https://github.com/neovim/neovim/pull/15134/files#diff-2c5241b87ba4cc10dd6d1822a2cfa718b1ea523bb9781da4f92585aff7f6b01fR1299

**Comment by WhoIsSethDaniel** [comment]
Sorry for the very late reply. While I continue to use this plugin I don't need to change it unless it breaks.  `enable`/`disable` only work on the current buffer. The approach I've taken for Neovim 0.7+ is to use `config` since it works across buffers (which is how this plugin works for 0.5 -> 0.6.1). This seems to work just fine. As long as this plugin works I don't see much need to change it. It does precisely what it was meant to do. I'll continue to fix bugs as they are reported, but I don't see a need to change how it works, for now.
