### ISSUE TITLE
config does not apply when start the neovim

### ISSUE THREAD

**Issue by alireza-constantin** [WhoIsSethDaniel/toggle-lsp-diagnostics.nvim#6]
even when I set config to true it doesn't turn on and I have to manually toggle-lsp-diag-default
`require'toggle_lsp_diagnostics'.init({ start_on = true }})`

**Comment by WhoIsSethDaniel** [comment]
Thanks. I will look at this soon.

**Comment by WhoIsSethDaniel** [comment]
apologies for taking so long to get back to you. Are you saying that your diagnostics start turned off?  That's very odd as, by default, they are turned on. And this is regardless of if you have this plugin installed.

Can you provide more details about what you are using? What version of neovim? Are you using a neovim distribution, like LunarVim or similar? 

I will look into this. It may be a simple fix. But I will likely need to know more. Thank you.

**Comment by WhoIsSethDaniel** [comment]
I am unable to duplicate this. If I turn everything off using `vim.diagnostic.config()` and then initialize this plugin everything is turned back on. I do not have to pass `{ start_on = true }` since that is the default (but it should be okay to do so). 

Perhaps a plugin you have, that is initialized later, turns the diagnostics off?

**Comment by samuelabreu** [comment]
For me using lunarvim, i had to create an autocmd, probably because of lazy.nvim

```lua
      vim.api.nvim_create_autocmd({"BufEnter", "BufWinEnter"}, {
        pattern = {"*.py"},
        callback = function()
          require 'toggle_lsp_diagnostics'.init({
            underline = false,
            virtual_text = false
          })
        end
      })
```
